name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Dodane zależności:
  flutter_background_service: # Do usług w tle
  permission_handler: # Do zarządzania uprawnieniami
  app_usage: # Do statystyk użycia
  shared_preferences: # Do przechowywania ustawień
  sqflite: # Lokalna baza danych
  path_provider: # Potrzebne dla sqflite
  path: # Do operacji na ścieżkach
  provider: ^6.1.1 # Do zarządzania stanem (użyłem konkretnej, stabilnej wersji)
  flutter_overlay_window: # Do wyświetlania nakładki
  device_apps: # Do listy zainstalowanych aplikacji
  uuid: ^4.0.0 # Do generowania unikalnych ID dla zadań

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
